# Generated by Django 5.2.3 on 2025-06-23 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employerprofile",
            name="zip_code",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="studentpractice",
            name="cancelled_by_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="studentpractice_cancelled_by_user_set",
                to="api.staguser",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(default="John", max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(default="Doe", max_length=50),
            preserve_default=False,
        ),
    ]
