# Generated by Django 5.2.3 on 2025-06-25 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_employerprofile_zip_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employerprofile",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
