# Generated by Django 5.2.3 on 2025-06-25 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_employerprofile_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employerprofile",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="images/logos"),
        ),
    ]
