# Generated by Django 5.2.3 on 2025-06-25 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_employerprofile_logo"),
    ]

    operations = [
        migrations.RunSQL(
            """
            INSERT INTO organizationrole (id, role, role_name)
            VALUES
                (1, 'owner', 'Owner'),
                (2, 'inserter','Inserter'),
                (3, 'unregistered','Unregistered')
            ON CONFLICT (id) DO NOTHING;
            """,
            reverse_sql="""
               DELETE FROM organizationrole WHERE id IN (1, 2, 3);
               """,
        ),
    ]
