# Generated by Django 5.2.3 on 2025-06-29 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_employerprofile_city_practiceuser_semester_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="date_joined",
            field=models.DateField(blank=True, null=True),
        ),
    ]
