# Generated by Django 5.2.4 on 2025-07-04 08:00

import api.models
import django_enumfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_user_date_joined"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="uploadeddocument",
            name="document_name",
        ),
        migrations.RemoveField(
            model_name="uploadeddocument",
            name="file_path",
        ),
        migrations.AddField(
            model_name="uploadeddocument",
            name="document",
            field=models.FileField(blank=True, null=True, upload_to="documents"),
        ),
        migrations.AlterField(
            model_name="usersubject",
            name="role",
            field=django_enumfield.db.fields.EnumField(default=0, enum=api.models.UserSubjectType),
            preserve_default=False,
        ),
    ]
