# Generated by Django 5.2.4 on 2025-07-04 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_remove_uploadeddocument_document_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employerprofile",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="storage/images/logos"),
        ),
        migrations.AlterField(
            model_name="uploadeddocument",
            name="document",
            field=models.FileField(blank=True, null=True, upload_to="storage/documents"),
        ),
    ]
