# Generated by Django 5.2.4 on 2025-07-06 17:00

import api.models
import django.db.models.deletion
import django_enumfield.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_alter_employerprofile_logo_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="staguser",
            name="additional_info",
        ),
        migrations.RemoveField(
            model_name="staguser",
            name="city",
        ),
        migrations.RemoveField(
            model_name="staguser",
            name="date_of_birth",
        ),
        migrations.RemoveField(
            model_name="staguser",
            name="field_of_study",
        ),
        migrations.RemoveField(
            model_name="staguser",
            name="os_cislo",
        ),
        migrations.RemoveField(
            model_name="staguser",
            name="place_of_birth",
        ),
        migrations.RemoveField(
            model_name="staguser",
            name="profile_picture",
        ),
        migrations.RemoveField(
            model_name="staguser",
            name="resume",
        ),
        migrations.RemoveField(
            model_name="staguser",
            name="specialization",
        ),
        migrations.RemoveField(
            model_name="staguser",
            name="stag_f_number",
        ),
        migrations.RemoveField(
            model_name="staguser",
            name="street",
        ),
        migrations.RemoveField(
            model_name="staguser",
            name="street_number",
        ),
        migrations.RemoveField(
            model_name="staguser",
            name="year_of_study",
        ),
        migrations.RemoveField(
            model_name="staguser",
            name="zip_code",
        ),
        migrations.CreateModel(
            name="ProfessorUser",
            fields=[
                (
                    "staguser_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="api.staguser",
                    ),
                ),
                (
                    "department_role",
                    django_enumfield.db.fields.EnumField(blank=True, enum=api.models.DepartmentRole, null=True),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="api.department",
                    ),
                ),
            ],
            options={
                "db_table": "professoruser",
            },
            bases=("api.staguser",),
            managers=[
                ("objects", api.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="StudentUser",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("profile_picture", models.TextField(blank=True, null=True)),
                (
                    "os_cislo",
                    models.CharField(blank=True, max_length=64, null=True, unique=True),
                ),
                (
                    "field_of_study",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("year_of_study", models.IntegerField(blank=True, null=True)),
                (
                    "stag_f_number",
                    models.IntegerField(blank=True, null=True, unique=True),
                ),
                ("resume", models.TextField(blank=True, null=True)),
                ("additional_info", models.TextField(blank=True, null=True)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "place_of_birth",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("street", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "street_number",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("zip_code", models.CharField(blank=True, max_length=10, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "specialization",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "stag_role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="api.stagrole",
                    ),
                ),
            ],
            options={
                "db_table": "studentuser",
            },
            bases=("api.user",),
            managers=[
                ("objects", api.models.UserManager()),
            ],
        ),
        migrations.DeleteModel(
            name="DepartmentUserRole",
        ),
    ]
