# Generated by Django 5.2.4 on 2025-07-07 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_rename_ucit_idno_professoruser_ucitidno"),
    ]

    operations = [
        migrations.RenameField(
            model_name="professoruser",
            old_name="ucitIdno",
            new_name="ucit_idno",
        ),
    ]
