# Generated by Django 5.2.4 on 2025-07-08 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_alter_employerinvitation_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentuser",
            name="practices",
            field=models.ManyToManyField(through="api.PracticeUser", to="api.practice"),
        ),
        migrations.AlterField(
            model_name="practiceuser",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="api.studentuser",
            ),
        ),
        migrations.AlterField(
            model_name="studentpractice",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="api.studentuser",
            ),
        ),
    ]
