# Generated by Django 5.2.4 on 2025-07-08 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_studentuser_practices_alter_practiceuser_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employerinvitation",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="api.studentuser",
            ),
        ),
    ]
