# Generated by Django 5.2.4 on 2025-07-08 18:13

import django.db.models.deletion
from django.db import migrations, models


def truncate_student_user_model(apps, schema_editor):
    connection = schema_editor.connection
    cursor = connection.cursor()
    cursor.execute('TRUNCATE TABLE "usersubject" CASCADE;')
    cursor.execute('TRUNCATE TABLE "studentuser" CASCADE;')


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_studentpractice_semester_studentpractice_year_and_more"),
    ]

    operations = [
        migrations.RunPython(truncate_student_user_model),
        migrations.RemoveField(
            model_name="studentuser",
            name="stag_role",
        ),
        migrations.RemoveField(
            model_name="studentuser",
            name="user_ptr",
        ),
        migrations.AddField(
            model_name="studentuser",
            name="staguser_ptr",
            field=models.OneToOneField(
                auto_created=True,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="api.staguser",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="employerinvitation",
            name="employer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="employer_invitations",
                to="api.employerprofile",
            ),
        ),
        migrations.AlterField(
            model_name="employerinvitation",
            name="practice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="employer_invitations",
                to="api.practice",
            ),
        ),
        migrations.AlterField(
            model_name="employerinvitation",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="employer_invitations",
                to="api.studentuser",
            ),
        ),
        migrations.AlterField(
            model_name="organizationuser",
            name="organization_role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="organization_users",
                to="api.organizationrole",
            ),
        ),
        migrations.AlterField(
            model_name="professoruser",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="professor_users",
                to="api.department",
            ),
        ),
        migrations.AlterField(
            model_name="studentuser",
            name="practices",
            field=models.ManyToManyField(
                related_name="student_users",
                through="api.StudentPractice",
                to="api.practice",
            ),
        ),
        migrations.AlterField(
            model_name="usersubject",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="user_subjects",
                to="api.subject",
            ),
        ),
        migrations.AlterField(
            model_name="usersubject",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="user_subjects",
                to="api.staguser",
            ),
        ),
    ]
