# Generated by Django 5.2.4 on 2025-07-08 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_remove_studentuser_stag_role_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="actionlog",
            table="action_logs",
        ),
        migrations.AlterModelTable(
            name="department",
            table="departments",
        ),
        migrations.AlterModelTable(
            name="employerinvitation",
            table="employer_invitations",
        ),
        migrations.AlterModelTable(
            name="employerprofile",
            table="employer_profiles",
        ),
        migrations.AlterModelTable(
            name="organizationrole",
            table="organization_roles",
        ),
        migrations.AlterModelTable(
            name="organizationuser",
            table="organization_users",
        ),
        migrations.AlterModelTable(
            name="practice",
            table="practices",
        ),
        migrations.AlterModelTable(
            name="practicetype",
            table="practice_types",
        ),
        migrations.AlterModelTable(
            name="professoruser",
            table="professor_users",
        ),
        migrations.AlterModelTable(
            name="role",
            table="roles",
        ),
        migrations.AlterModelTable(
            name="stagrole",
            table="stag_roles",
        ),
        migrations.AlterModelTable(
            name="staguser",
            table="stag_users",
        ),
        migrations.AlterModelTable(
            name="status",
            table="statuses",
        ),
        migrations.AlterModelTable(
            name="studentpractice",
            table="student_practices",
        ),
        migrations.AlterModelTable(
            name="studentuser",
            table="student_users",
        ),
        migrations.AlterModelTable(
            name="subject",
            table="subjects",
        ),
        migrations.AlterModelTable(
            name="uploadeddocument",
            table="uploaded_documents",
        ),
        migrations.AlterModelTable(
            name="user",
            table="users",
        ),
        migrations.AlterModelTable(
            name="usersubject",
            table="user_subjects",
        ),
    ]
