# Generated by Django 5.2.4 on 2025-07-08 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0019_alter_actionlog_table_alter_department_table_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="practice",
            old_name="status",
            new_name="progress_status",
        ),
    ]
