# Generated by Django 5.2.4 on 2025-07-13 09:07

import api.models
import django_enumfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0020_rename_status_practice_progress_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizationuser",
            name="organization_role",
            field=django_enumfield.db.fields.EnumField(blank=True, enum=api.models.OrganizationRole, null=True),
        ),
        migrations.DeleteModel(
            name="OrganizationRole",
        ),
    ]
