# Generated by Django 5.2.4 on 2025-07-13 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0021_alter_organizationuser_organization_role_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Status",
        ),
    ]
