# Generated by Django 5.2.4 on 2025-07-17 15:47
import django_enumfield.db.fields
from django.db import migrations
from django_enumfield import enum


class Migration(migrations.Migration):
    class SemesterType(enum.Enum):
        WINTER = 0
        SUMMER = 1

    dependencies = [
        ("api", "0022_delete_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentpractice",
            name="semester",
            field=django_enumfield.db.fields.EnumField(enum=SemesterType, null=True),
        ),
    ]
