# Generated by Django 5.2.4 on 2025-07-17 15:47

import api.models
import django_enumfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0022_delete_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentpractice",
            name="semester",
            field=django_enumfield.db.fields.EnumField(
                enum=api.models.SemesterType, null=True
            ),
        ),
    ]
