# Generated by Django 5.2.4 on 2025-07-18 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0024_employerinvitation_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentpractice",
            name="semester",
        ),
    ]
