# Generated by Django 5.2.4 on 2025-07-22 16:40

import api.models
import django.db.models.deletion
import django_enumfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0025_remove_studentpractice_semester"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="uploadeddocument",
            name="practice",
        ),
        migrations.AddField(
            model_name="studentpractice",
            name="content_document",
            field=models.OneToOneField(
                blank=True,
                limit_choices_to={"document_type": api.models.DocumentType(1)},
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="student_practice_content",
                to="api.uploadeddocument",
                validators=[api.models.StudentPractice.validate_content_document_type],
            ),
        ),
        migrations.AddField(
            model_name="studentpractice",
            name="contract_document",
            field=models.OneToOneField(
                blank=True,
                limit_choices_to={"document_type": api.models.DocumentType(0)},
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="student_practice_contract",
                to="api.uploadeddocument",
                validators=[api.models.StudentPractice.validate_contract_document_type],
            ),
        ),
        migrations.RunPython(lambda apps, schema_editor: apps.get_model("api", "UploadedDocument").objects.all().delete()),
        migrations.AddField(
            model_name="studentpractice",
            name="feedback_document",
            field=models.OneToOneField(
                blank=True,
                limit_choices_to={"document_type": api.models.DocumentType(2)},
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="student_practice_feedback",
                to="api.uploadeddocument",
                validators=[api.models.StudentPractice.validate_feedback_document_type],
            ),
        ),
        migrations.AlterField(
            model_name="uploadeddocument",
            name="document_type",
            field=django_enumfield.db.fields.EnumField(default=0, enum=api.models.DocumentType),
            preserve_default=False,
        ),
    ]
