# Generated by Django 5.2.4 on 2025-07-22 17:25
import os

import api.models
import django.db.models.deletion
from app import settings
from django.core.files import File
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    def generate_default_documents(apps, schema_editor):
        UploadedDocument = apps.get_model("api", "UploadedDocument")
        StudentPractice = apps.get_model("api", "StudentPractice")

        default_dir = os.path.join(settings.BASE_DIR, "storage", "default_documents")
        mapping = {
            "contract_document": ("default_contract.docx", 0),
            "content_document": ("default_content.docx", 1),
            "feedback_document": ("default_feedback.docx", 2),
        }

        for field, (filename, doc_type) in mapping.items():
            path = os.path.join(default_dir, filename)
            qs = StudentPractice.objects.filter(**{f"{field}__isnull": True})
            for sp in qs:
                with open(path, "rb") as f:
                    upload = UploadedDocument(document_type=doc_type, document=File(f, name=filename))
                    upload.save()
                setattr(sp, field + "_id", upload.pk)
                sp.save(update_fields=[field])

    dependencies = [
        ("api", "0026_remove_uploadeddocument_practice_and_more"),
    ]

    operations = [
        migrations.RunPython(generate_default_documents, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="studentpractice",
            name="content_document",
            field=models.OneToOneField(
                limit_choices_to={"document_type": api.models.DocumentType(1)},
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="student_practice_content",
                to="api.uploadeddocument",
                validators=[api.models.StudentPractice.validate_content_document_type],
            ),
        ),
        migrations.AlterField(
            model_name="studentpractice",
            name="contract_document",
            field=models.OneToOneField(
                limit_choices_to={"document_type": api.models.DocumentType(0)},
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="student_practice_contract",
                to="api.uploadeddocument",
                validators=[api.models.StudentPractice.validate_contract_document_type],
            ),
        ),
        migrations.AlterField(
            model_name="studentpractice",
            name="feedback_document",
            field=models.OneToOneField(
                limit_choices_to={"document_type": api.models.DocumentType(2)},
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="student_practice_feedback",
                to="api.uploadeddocument",
                validators=[api.models.StudentPractice.validate_feedback_document_type],
            ),
        ),
    ]
