# Generated by Django 5.2.4 on 2025-07-23 05:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0027_alter_studentpractice_content_document_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentpractice",
            name="end_date",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="studentpractice",
            name="start_date",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
