# Generated by Django 5.2.4 on 2025-07-25 11:46
import uuid

from django.db import migrations, models


def backfill_codes(apps, schema_editor):
    Department = apps.get_model("api", "Department")
    for dept in Department.objects.all():
        if dept.department_name is None:
            dept.department_name = uuid.uuid4().hex
        if dept.department_code is None:
            dept.department_code = uuid.uuid4().hex
        dept.save(update_fields=["department_code", "department_name"])


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0028_studentpractice_end_date_studentpractice_start_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="department_code",
            field=models.CharField(max_length=100, unique=True, null=True, blank=True),
            preserve_default=False,
        ),
        migrations.RunPython(backfill_codes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="department",
            name="department_name",
            field=models.CharField(max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="department",
            name="department_code",
            field=models.CharField(max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
