# Generated by Django 5.2.4 on 2025-07-27 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0029_department_department_code_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="practice",
            name="practice_type",
        ),
        migrations.AddField(
            model_name="practice",
            name="coefficient",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="PracticeType",
        ),
    ]
