# Generated by Django 6.0 on 2025-12-06 19:18

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_add_subject_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionlog',
            name='action_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='action_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='object_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='department',
            name='department_code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='department_name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='employerinvitation',
            name='message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='city',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='company_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='company_profile',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='practice',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='practice',
            name='image_base64',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='practice',
            name='responsibilities',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='practice',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='role',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='stagrole',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='studentpractice',
            name='cancellation_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='studentpractice',
            name='content_document',
            field=models.OneToOneField(limit_choices_to={'document_type': api.models.DocumentType(1)}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='student_practice_content', to='api.uploadeddocument'),
        ),
        migrations.AlterField(
            model_name='studentpractice',
            name='contract_document',
            field=models.OneToOneField(limit_choices_to={'document_type': api.models.DocumentType(0)}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='student_practice_contract', to='api.uploadeddocument'),
        ),
        migrations.AlterField(
            model_name='studentpractice',
            name='feedback_document',
            field=models.OneToOneField(limit_choices_to={'document_type': api.models.DocumentType(2)}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='student_practice_feedback', to='api.uploadeddocument'),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='additional_info',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='field_of_study',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='place_of_birth',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='profile_picture',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='resume',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='specialization',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='street',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='street_number',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='zip_code',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='title_after',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='title_before',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
