repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
        files: ^(backend|frontend)/
    -   id: end-of-file-fixer
        files: ^(backend|frontend)/
    -   id: check-yaml
        files: ^(backend|frontend)/
-   repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.8.2
    hooks:
    # Run the linter.
    -   id: ruff
        files: ^backend/
        args: [ --fix ]
    # Run the formatter.
    -   id: ruff-format
        files: ^backend/
-   repo: local
    hooks:
    -   id: eslint-frontend
        name: ESLint (frontend)
        language: node
        entry: bash -c 'cd frontend && npx eslint src --ext .js,.jsx'
        files: ^frontend/src/.*\.(js|jsx)$
        pass_filenames: false