repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
        files: ^backend/
    -   id: end-of-file-fixer
        files: ^backend/
    -   id: check-yaml
        files: ^backend/
-   repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
    -   id: isort
        files: ^backend/
-   repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.1.1
    hooks:
    -   id: black
        language_version: python3.13
        args: ["--line-length=140"]
        files: ^backend/
-   repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
    -   id: flake8
        files: ^backend/
        args: ["--max-line-length=140"]