services:
  postgres:
    image: postgres:17
    container_name: internhub-postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${PG_DB}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    expose:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $PG_USER -d $PG_DB"]
      interval: 10s
      timeout: 10s
      retries: 30
    networks:
      - internhub

  django:
    build:
      context: .
      dockerfile: .docker/Backend/Dockerfile
      args:
        - PY_VERSION=${PY_VERSION}
    container_name: internhub-backend
    restart: unless-stopped
    command: gunicorn app.wsgi:application --bind 0.0.0.0:8000 --workers 4
    env_file:
      - .env
    volumes:
      - storage_data:/app/backend/storage
      - ./backend:/app/backend
    expose:
      - "8000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - internhub

  frontend:
    build:
      context: .
      dockerfile: .docker/Frontend/Dockerfile.prod
      args:
        - NODE_VERSION=${NODE_VERSION}
    container_name: internhub-frontend
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - storage_data:/usr/share/nginx/html/storage:ro
    depends_on:
      - django
    networks:
      - internhub

networks:
  internhub:
    name: internhub
    driver: bridge

volumes:
  postgres_data:
  storage_data:
