# Generated by Django 6.0 on 2025-12-07 15:44

import django.db.models.deletion
import student_practices.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("practices", "0002_initial"),
        ("student_practices", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employerinvitation",
            name="employer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employer_invitations",
                to="users.employerprofile",
            ),
        ),
        migrations.AddField(
            model_name="employerinvitation",
            name="practice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employer_invitations",
                to="practices.practice",
            ),
        ),
        migrations.AddField(
            model_name="employerinvitation",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employer_invitations",
                to="users.studentuser",
            ),
        ),
        migrations.AddField(
            model_name="studentpractice",
            name="cancelled_by_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cancelled_student_practices",
                to="users.staguser",
            ),
        ),
        migrations.AddField(
            model_name="studentpractice",
            name="practice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_practices",
                to="practices.practice",
            ),
        ),
        migrations.AddField(
            model_name="studentpractice",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_practices",
                to="users.studentuser",
            ),
        ),
        migrations.AddField(
            model_name="studentpractice",
            name="content_document",
            field=models.OneToOneField(
                limit_choices_to={
                    "document_type": student_practices.models.DocumentType(1)
                },
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_practice_content",
                to="student_practices.uploadeddocument",
            ),
        ),
        migrations.AddField(
            model_name="studentpractice",
            name="contract_document",
            field=models.OneToOneField(
                limit_choices_to={
                    "document_type": student_practices.models.DocumentType(0)
                },
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_practice_contract",
                to="student_practices.uploadeddocument",
            ),
        ),
        migrations.AddField(
            model_name="studentpractice",
            name="feedback_document",
            field=models.OneToOneField(
                limit_choices_to={
                    "document_type": student_practices.models.DocumentType(2)
                },
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_practice_feedback",
                to="student_practices.uploadeddocument",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="studentpractice",
            unique_together={("user", "practice")},
        ),
    ]
