# Generated by Django 5.2.11 on 2026-02-28 21:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student_practices", "0004_uploadeddocument_document_db_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentpractice",
            name="employer_approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="studentpractice",
            name="school_approved",
            field=models.BooleanField(default=False),
        ),
    ]
