# Generated by Django 5.2.12 on 2026-03-07 12:58

import django_enumfield.db.fields
import student_practices.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student_practices", "0005_studentpractice_employer_approved_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadeddocument",
            name="review_note",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="uploadeddocument",
            name="status",
            field=django_enumfield.db.fields.EnumField(
                default=0, enum=student_practices.models.DocumentStatus
            ),
        ),
    ]
