export default stagUsers = [
  {
    "user_id": 5,
    "password": "hashed_password_345",
    "username": "f20b0539p",
    "email": "f20b0539p@students.zcu.cz",
    "title_before": "Bc.",
    "first_name": "Jan",
    "last_name": "Novák",
    "title_after": "",
    "phone": "+420 123 456 789",
    "is_active": true,
    "is_superuser": false,
    "is_staff": false,
    "activated_at": "2023-09-01T00:00:00Z",
    "created_at": "2023-09-01T00:00:00Z",
    "updated_at": "2023-12-01T00:00:00Z",
    "profile_picture": "https://via.placeholder.com/150",
    "field_of_study": "Informatika",
    "year_of_study": 3,
    "stag_f_number": 20200539,
    "resume": "Zkušenosti s programováním v JavaScript, React, Node.js. Praxe v IT firmě během letních prázdnin.",
    "additional_info": "Zajímám se o webový vývoj a umělou inteligenci. Aktivní člen studentského klubu.",
    "date_of_birth": "2002-05-15",
    "place_of_birth": "Praha",
    "street": "Nerudova",
    "street_number": "15",
    "zip_code": "11800",
    "city": "Praha",
    "specialization": "Webové technologie",
    "stag_role": 1
  },
  {
    "user_id": 6,
    "password": "hashed_password_678",
    "username": "f21b1234p",
    "email": "f21b1234p@students.zcu.cz",
    "title_before": "Bc.",
    "first_name": "Anna",
    "last_name": "Svobodová",
    "title_after": "",
    "phone": "+420 987 654 321",
    "is_active": true,
    "is_superuser": false,
    "is_staff": false,
    "activated_at": "2023-09-01T00:00:00Z",
    "created_at": "2023-09-01T00:00:00Z",
    "updated_at": "2023-12-01T00:00:00Z",
    "profile_picture": "https://via.placeholder.com/150",
    "field_of_study": "Aplikovaná informatika",
    "year_of_study": 2,
    "stag_f_number": 20211234,
    "resume": "Základní znalosti Python, Java, databáze. Účast na hackathonu.",
    "additional_info": "Zajímám se o datovou analýzu a strojové učení.",
    "date_of_birth": "2003-08-22",
    "place_of_birth": "Brno",
    "street": "Kounicova",
    "street_number": "8",
    "zip_code": "60200",
    "city": "Brno",
    "specialization": "Datová analýza",
    "stag_role": 1
  }
] 