export default students = [
    {
        "id": 1,
        "username": "f20b0539p",
        "email": "f20b0539p@students.zcu.cz",
        "title_before": "Bc.",
        "first_name": "Jan",
        "last_name": "Novák",
        "title_after": "",
        "phone": "+420 123 456 789",
        "date_joined": "2023-09-01T00:00:00Z",
        "is_active": true,
        "profile_picture": "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fprofile%2520icon%2F&psig=AOvVaw2AQtiD3GqKEFpRiaGLCAng&ust=1751044051684000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCNjNksjJj44DFQAAAAAdAAAAABAE",
        "field_of_study": "Informatika",
        "year_of_study": 3,
        "stag_f_number": 20200539,
        "resume": "Zkušenosti s programováním v JavaScript, React, Node.js. Praxe v IT firmě během letních prázdnin.",
        "additional_info": "Zajímám se o webový vývoj a umělou inteligenci. Aktivní člen studentského klubu.",
        "date_of_birth": "2002-05-15",
        "place_of_birth": "Praha",
        "street": "Nerudova",
        "street_number": "15",
        "zip_code": "11800",
        "city": "Praha",
        "specialization": "Webové technologie",
        "role": "ST",
        "role_name": "Student",
        "faculty": "FF",
        "os_cislo": "F20B0539P"
    }
]