--
-- --
-- -- PostgreSQL database dump
-- --
--
-- -- Dumped from database version 17.4 (Debian 17.4-1.pgdg120+2)
-- -- Dumped by pg_dump version 17.5
--
-- -- Started on 2025-08-01 18:16:06 CEST
--
SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;
--
-- --
-- -- TOC entry 5 (class 2615 OID 2200)
-- -- Name: public; Type: SCHEMA; Schema: -; Owner: internhub
-- --
--
-- -- *not* creating schema, since initdb creates it
--
--
ALTER SCHEMA public OWNER TO internhub;
--
-- --
-- -- TOC entry 3717 (class 0 OID 0)
-- -- Dependencies: 5
-- -- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: internhub
-- --
--
COMMENT ON SCHEMA public IS '';
--
--
SET default_tablespace = '';
--
SET default_table_access_method = heap;
--
-- --
-- -- TOC entry 217 (class 1259 OID 24578)
-- -- Name: action_logs; Type: TABLE; Schema: public; Owner: internhub
-- --
--
CREATE TABLE public.action_logs (
    action_id integer NOT NULL,
    action_type character varying(50),
    object_type character varying(50),
    object_id integer,
    action_description text,
    action_date timestamp with time zone,
    user_id integer
);
--
--
ALTER TABLE public.action_logs OWNER TO internhub;
--
-- --
-- -- TOC entry 218 (class 1259 OID 24583)
-- -- Name: actionlog_action_id_seq; Type: SEQUENCE; Schema: public; Owner: internhub
-- --
--
ALTER TABLE public.action_logs ALTER COLUMN action_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.actionlog_action_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
--
--
-- --
-- -- TOC entry 219 (class 1259 OID 24584)
-- -- Name: auth_group; Type: TABLE; Schema: public; Owner: internhub
-- --
--
CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);
--
--
ALTER TABLE public.auth_group OWNER TO internhub;
--
-- --
-- -- TOC entry 220 (class 1259 OID 24587)
-- -- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: internhub
-- --
--
ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
--
--
-- --
-- -- TOC entry 221 (class 1259 OID 24588)
-- -- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: internhub
-- --
--
CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);
--
--
ALTER TABLE public.auth_group_permissions OWNER TO internhub;
--
-- --
-- -- TOC entry 222 (class 1259 OID 24591)
-- -- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: internhub
-- --
--
ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
--
--
-- --
-- -- TOC entry 223 (class 1259 OID 24592)
-- -- Name: auth_permission; Type: TABLE; Schema: public; Owner: internhub
-- --
--
CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);
--
--
ALTER TABLE public.auth_permission OWNER TO internhub;
--
-- --
-- -- TOC entry 224 (class 1259 OID 24595)
-- -- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: internhub
-- --
--
ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
--
--
-- --
-- -- TOC entry 225 (class 1259 OID 24596)
-- -- Name: departments; Type: TABLE; Schema: public; Owner: internhub
-- --
--
CREATE TABLE public.departments (
    department_id integer NOT NULL,
    department_name character varying(100) NOT NULL,
    description text,
    department_code character varying(100) NOT NULL
);
--
--
ALTER TABLE public.departments OWNER TO internhub;
--
-- --
-- -- TOC entry 226 (class 1259 OID 24601)
-- -- Name: department_department_id_seq; Type: SEQUENCE; Schema: public; Owner: internhub
-- --
--
ALTER TABLE public.departments ALTER COLUMN department_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.department_department_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
--
--
-- --
-- -- TOC entry 227 (class 1259 OID 24602)
-- -- Name: django_admin_log; Type: TABLE; Schema: public; Owner: internhub
-- --
--
CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);
--
--
ALTER TABLE public.django_admin_log OWNER TO internhub;
--
-- --
-- -- TOC entry 228 (class 1259 OID 24608)
-- -- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: internhub
-- --
--
ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
--
--
-- --
-- -- TOC entry 229 (class 1259 OID 24609)
-- -- Name: django_content_type; Type: TABLE; Schema: public; Owner: internhub
-- --
--
CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);
--
--
ALTER TABLE public.django_content_type OWNER TO internhub;
--
-- --
-- -- TOC entry 230 (class 1259 OID 24612)
-- -- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: internhub
-- --
--
ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
--
--
-- --
-- -- TOC entry 231 (class 1259 OID 24613)
-- -- Name: django_migrations; Type: TABLE; Schema: public; Owner: internhub
-- --
--
CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);
--
--
ALTER TABLE public.django_migrations OWNER TO internhub;
--
-- --
-- -- TOC entry 232 (class 1259 OID 24618)
-- -- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: internhub
-- --
--
ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
--
--
-- --
-- -- TOC entry 233 (class 1259 OID 24619)
-- -- Name: django_session; Type: TABLE; Schema: public; Owner: internhub
-- --
--
CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);
--
--
ALTER TABLE public.django_session OWNER TO internhub;
--
-- --
-- -- TOC entry 234 (class 1259 OID 24624)
-- -- Name: employer_invitations; Type: TABLE; Schema: public; Owner: internhub
-- --
--
CREATE TABLE public.employer_invitations (
    invitation_id integer NOT NULL,
    submission_date date,
    expiration_date date,
    message text,
    employer_id integer,
    practice_id integer,
    status integer NOT NULL,
    user_id integer,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);
--
--
ALTER TABLE public.employer_invitations OWNER TO internhub;
--
-- --
-- -- TOC entry 235 (class 1259 OID 24629)
-- -- Name: employer_profiles; Type: TABLE; Schema: public; Owner: internhub
-- --
--
CREATE TABLE public.employer_profiles (
    employer_id integer NOT NULL,
    company_name character varying(100),
    ico character varying(15),
    dic character varying(15),
    address text,
    company_profile text,
    approval_status integer NOT NULL,
    zip_code integer,
    logo character varying(100),
    city text,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);
--
--
ALTER TABLE public.employer_profiles OWNER TO internhub;
--
-- --
-- -- TOC entry 236 (class 1259 OID 24634)
-- -- Name: employerinvitation_invitation_id_seq; Type: SEQUENCE; Schema: public; Owner: internhub
-- --
--
ALTER TABLE public.employer_invitations ALTER COLUMN invitation_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.employerinvitation_invitation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
--
--
-- --
-- -- TOC entry 237 (class 1259 OID 24635)
-- -- Name: employerprofile_employer_id_seq; Type: SEQUENCE; Schema: public; Owner: internhub
-- --
--
ALTER TABLE public.employer_profiles ALTER COLUMN employer_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.employerprofile_employer_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
--
--
-- --
-- -- TOC entry 238 (class 1259 OID 24636)
-- -- Name: organization_users; Type: TABLE; Schema: public; Owner: internhub
-- --
--
CREATE TABLE public.organization_users (
    user_ptr_id integer NOT NULL,
    employer_profile_id integer,
    organization_role integer
);
--
--
ALTER TABLE public.organization_users OWNER TO internhub;
--
-- --
-- -- TOC entry 239 (class 1259 OID 24639)
-- -- Name: practices; Type: TABLE; Schema: public; Owner: internhub
-- --
--
CREATE TABLE public.practices (
    practice_id integer NOT NULL,
    title character varying(100),
    description text,
    responsibilities text,
    available_positions integer,
    start_date date,
    end_date date,
    is_active boolean,
    image_base64 text,
    employer_id integer,
    approval_status integer NOT NULL,
    progress_status integer NOT NULL,
    subject_id integer,
    contact_user_id integer,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    coefficient double precision NOT NULL
);
--
--
ALTER TABLE public.practices OWNER TO internhub;
--
-- --
-- -- TOC entry 240 (class 1259 OID 24644)
-- -- Name: practice_practice_id_seq; Type: SEQUENCE; Schema: public; Owner: internhub
-- --
--
ALTER TABLE public.practices ALTER COLUMN practice_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.practice_practice_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
--
--
-- --
-- -- TOC entry 241 (class 1259 OID 24645)
-- -- Name: professor_users; Type: TABLE; Schema: public; Owner: internhub
-- --
--
CREATE TABLE public.professor_users (
    staguser_ptr_id integer NOT NULL,
    department_role integer,
    department_id integer,
    ucit_idno character varying(64)
);
--
--
ALTER TABLE public.professor_users OWNER TO internhub;
--
-- --
-- -- TOC entry 242 (class 1259 OID 24648)
-- -- Name: roles; Type: TABLE; Schema: public; Owner: internhub
-- --
--
CREATE TABLE public.roles (
    role_id integer NOT NULL,
    role_name character varying(50),
    description text
);
--
--
ALTER TABLE public.roles OWNER TO internhub;
--
-- --
-- -- TOC entry 243 (class 1259 OID 24653)
-- -- Name: role_role_id_seq; Type: SEQUENCE; Schema: public; Owner: internhub
-- --
--
ALTER TABLE public.roles ALTER COLUMN role_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.role_role_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
--
--
-- --
-- -- TOC entry 244 (class 1259 OID 24654)
-- -- Name: stag_roles; Type: TABLE; Schema: public; Owner: internhub
-- --
--
CREATE TABLE public.stag_roles (
    id integer NOT NULL,
    role character varying NOT NULL,
    role_name character varying(50),
    description text
);
--
--
ALTER TABLE public.stag_roles OWNER TO internhub;
--
-- --
-- -- TOC entry 245 (class 1259 OID 24659)
-- -- Name: stag_users; Type: TABLE; Schema: public; Owner: internhub
-- --
--
CREATE TABLE public.stag_users (
    user_ptr_id integer NOT NULL,
    stag_role_id integer
);
--
--
ALTER TABLE public.stag_users OWNER TO internhub;
--
-- --
-- -- TOC entry 246 (class 1259 OID 24662)
-- -- Name: stagrole_id_seq; Type: SEQUENCE; Schema: public; Owner: internhub
-- --
--
ALTER TABLE public.stag_roles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.stagrole_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
--
--
-- --
-- -- TOC entry 247 (class 1259 OID 24663)
-- -- Name: student_practices; Type: TABLE; Schema: public; Owner: internhub
-- --
--
CREATE TABLE public.student_practices (
    student_practice_id integer NOT NULL,
    application_date date,
    hours_completed integer,
    cancellation_reason text,
    approval_status integer NOT NULL,
    cancelled_by_user_id integer,
    practice_id integer,
    progress_status integer NOT NULL,
    user_id integer,
    year integer,
    content_document_id integer NOT NULL,
    contract_document_id integer NOT NULL,
    feedback_document_id integer NOT NULL,
    end_date date NOT NULL,
    start_date date NOT NULL
);
--
--
ALTER TABLE public.student_practices OWNER TO internhub;
--
-- --
-- -- TOC entry 248 (class 1259 OID 24668)
-- -- Name: student_users; Type: TABLE; Schema: public; Owner: internhub
-- --
--
CREATE TABLE public.student_users (
    profile_picture text,
    os_cislo character varying(64),
    field_of_study character varying(100),
    year_of_study integer,
    stag_f_number integer,
    resume text,
    additional_info text,
    date_of_birth date,
    place_of_birth character varying(100),
    street character varying(100),
    street_number character varying(10),
    zip_code character varying(10),
    city character varying(100),
    specialization character varying(100),
    staguser_ptr_id integer NOT NULL
);
--
--
ALTER TABLE public.student_users OWNER TO internhub;
--
-- --
-- -- TOC entry 249 (class 1259 OID 24673)
-- -- Name: studentpractice_student_practice_id_seq; Type: SEQUENCE; Schema: public; Owner: internhub
-- --
--
ALTER TABLE public.student_practices ALTER COLUMN student_practice_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.studentpractice_student_practice_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
--
--
-- --
-- -- TOC entry 250 (class 1259 OID 24674)
-- -- Name: subjects; Type: TABLE; Schema: public; Owner: internhub
-- --
--
CREATE TABLE public.subjects (
    subject_id integer NOT NULL,
    subject_code character varying(50),
    subject_name character varying(100),
    hours_required integer,
    department_id integer
);
--
--
ALTER TABLE public.subjects OWNER TO internhub;
--
-- --
-- -- TOC entry 251 (class 1259 OID 24677)
-- -- Name: subject_subject_id_seq; Type: SEQUENCE; Schema: public; Owner: internhub
-- --
--
ALTER TABLE public.subjects ALTER COLUMN subject_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.subject_subject_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
--
--
-- --
-- -- TOC entry 252 (class 1259 OID 24678)
-- -- Name: token_blacklist_blacklistedtoken; Type: TABLE; Schema: public; Owner: internhub
-- --
--
CREATE TABLE public.token_blacklist_blacklistedtoken (
    id bigint NOT NULL,
    blacklisted_at timestamp with time zone NOT NULL,
    token_id bigint NOT NULL
);
--
--
ALTER TABLE public.token_blacklist_blacklistedtoken OWNER TO internhub;
--
-- --
-- -- TOC entry 253 (class 1259 OID 24681)
-- -- Name: token_blacklist_blacklistedtoken_id_seq; Type: SEQUENCE; Schema: public; Owner: internhub
-- --
--
ALTER TABLE public.token_blacklist_blacklistedtoken ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.token_blacklist_blacklistedtoken_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
--
--
-- --
-- -- TOC entry 254 (class 1259 OID 24682)
-- -- Name: token_blacklist_outstandingtoken; Type: TABLE; Schema: public; Owner: internhub
-- --
--
CREATE TABLE public.token_blacklist_outstandingtoken (
    id bigint NOT NULL,
    token text NOT NULL,
    created_at timestamp with time zone,
    expires_at timestamp with time zone NOT NULL,
    user_id integer,
    jti character varying(255) NOT NULL
);
--
--
ALTER TABLE public.token_blacklist_outstandingtoken OWNER TO internhub;
--
-- --
-- -- TOC entry 255 (class 1259 OID 24687)
-- -- Name: token_blacklist_outstandingtoken_id_seq; Type: SEQUENCE; Schema: public; Owner: internhub
-- --
--
ALTER TABLE public.token_blacklist_outstandingtoken ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.token_blacklist_outstandingtoken_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
--
--
-- --
-- -- TOC entry 256 (class 1259 OID 24688)
-- -- Name: uploaded_documents; Type: TABLE; Schema: public; Owner: internhub
-- --
--
CREATE TABLE public.uploaded_documents (
    document_id integer NOT NULL,
    uploaded_at timestamp with time zone,
    document_type integer NOT NULL,
    document character varying(100)
);
--
--
ALTER TABLE public.uploaded_documents OWNER TO internhub;
--
-- --
-- -- TOC entry 257 (class 1259 OID 24691)
-- -- Name: uploadeddocument_document_id_seq; Type: SEQUENCE; Schema: public; Owner: internhub
-- --
--
ALTER TABLE public.uploaded_documents ALTER COLUMN document_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.uploadeddocument_document_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
--
--
-- --
-- -- TOC entry 258 (class 1259 OID 24692)
-- -- Name: users_groups; Type: TABLE; Schema: public; Owner: internhub
-- --
--
CREATE TABLE public.users_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);
--
--
ALTER TABLE public.users_groups OWNER TO internhub;
--
-- --
-- -- TOC entry 259 (class 1259 OID 24695)
-- -- Name: user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: internhub
-- --
--
ALTER TABLE public.users_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
--
--
-- --
-- -- TOC entry 260 (class 1259 OID 24696)
-- -- Name: user_subjects; Type: TABLE; Schema: public; Owner: internhub
-- --
--
CREATE TABLE public.user_subjects (
    id integer NOT NULL,
    role integer NOT NULL,
    subject_id integer,
    user_id integer
);
--
--
ALTER TABLE public.user_subjects OWNER TO internhub;
--
-- --
-- -- TOC entry 261 (class 1259 OID 24699)
-- -- Name: users; Type: TABLE; Schema: public; Owner: internhub
-- --
--
CREATE TABLE public.users (
    last_login timestamp with time zone,
    user_id integer NOT NULL,
    password character varying(128),
    username character varying(150),
    email character varying(254) NOT NULL,
    title_before character varying(50),
    first_name character varying(50) NOT NULL,
    last_name character varying(50) NOT NULL,
    title_after character varying(50),
    phone character varying(15),
    is_active boolean NOT NULL,
    is_superuser boolean NOT NULL,
    is_staff boolean NOT NULL,
    activated_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    polymorphic_ctype_id integer,
    date_joined date
);
--
--
ALTER TABLE public.users OWNER TO internhub;
--
-- --
-- -- TOC entry 262 (class 1259 OID 24704)
-- -- Name: user_user_id_seq; Type: SEQUENCE; Schema: public; Owner: internhub
-- --
--
ALTER TABLE public.users ALTER COLUMN user_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
--
--
-- --
-- -- TOC entry 263 (class 1259 OID 24705)
-- -- Name: users_user_permissions; Type: TABLE; Schema: public; Owner: internhub
-- --
--
CREATE TABLE public.users_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);
--
--
ALTER TABLE public.users_user_permissions OWNER TO internhub;
--
-- --
-- -- TOC entry 264 (class 1259 OID 24708)
-- -- Name: user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: internhub
-- --
--
ALTER TABLE public.users_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
--
--
-- --
-- -- TOC entry 265 (class 1259 OID 24709)
-- -- Name: usersubject_id_seq; Type: SEQUENCE; Schema: public; Owner: internhub
-- --
--
ALTER TABLE public.user_subjects ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usersubject_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
--
--
--
-- --
-- -- TOC entry 3337 (class 2606 OID 24713)
-- -- Name: action_logs actionlog_pkey; Type: CONSTRAINT; Schema: public; Owner: internhub
-- --
--
ALTER TABLE ONLY public.action_logs
    ADD CONSTRAINT actionlog_pkey PRIMARY KEY (action_id);
--
--
-- --
-- -- TOC entry 3341 (class 2606 OID 24715)
-- -- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: internhub
-- --
--
ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);
--
--
-- --
-- -- TOC entry 3346 (class 2606 OID 24717)
-- -- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: internhub
-- --
--
ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);
--
--
-- --
-- -- TOC entry 3349 (class 2606 OID 24719)
-- -- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: internhub
-- --
--
ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);
--
--
-- --
-- -- TOC entry 3343 (class 2606 OID 24721)
-- -- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: internhub
-- --
--
ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);
--
--
-- --
-- -- TOC entry 3352 (class 2606 OID 24723)
-- -- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: internhub
-- --
--
ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);
--
--
-- --
-- -- TOC entry 3354 (class 2606 OID 24725)
-- -- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: internhub
-- --
--
ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);
--
--
-- --
-- -- TOC entry 3357 (class 2606 OID 24727)
-- -- Name: departments department_department_name_key; Type: CONSTRAINT; Schema: public; Owner: internhub
-- --
--
ALTER TABLE ONLY public.departments
    ADD CONSTRAINT department_department_name_key UNIQUE (department_name);
--
--
-- --
-- -- TOC entry 3359 (class 2606 OID 24729)
-- -- Name: departments department_pkey; Type: CONSTRAINT; Schema: public; Owner: internhub
-- --
--
ALTER TABLE ONLY public.departments
    ADD CONSTRAINT department_pkey PRIMARY KEY (department_id);
--
--
-- --
-- -- TOC entry 3362 (class 2606 OID 24731)
-- -- Name: departments departments_department_code_key; Type: CONSTRAINT; Schema: public; Owner: internhub
-- --
--
ALTER TABLE ONLY public.departments
    ADD CONSTRAINT departments_department_code_key UNIQUE (department_code);
--
--
-- --
-- -- TOC entry 3365 (class 2606 OID 24733)
-- -- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: internhub
-- --
--
ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);
--
--
-- --
-- -- TOC entry 3368 (class 2606 OID 24735)
-- -- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: internhub
-- --
--
ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);
--
--
-- --
-- -- TOC entry 3370 (class 2606 OID 24737)
-- -- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: internhub
-- --
--
ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);
--
--
-- --
-- -- TOC entry 3372 (class 2606 OID 24739)
-- -- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: internhub
-- --
--
ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);
--
--
-- --
-- -- TOC entry 3375 (class 2606 OID 24741)
-- -- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: internhub
-- --
--
ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);
--
--
-- --
-- -- TOC entry 3379 (class 2606 OID 24743)
-- -- Name: employer_invitations employerinvitation_pkey; Type: CONSTRAINT; Schema: public; Owner: internhub
-- --
--
ALTER TABLE ONLY public.employer_invitations
    ADD CONSTRAINT employerinvitation_pkey PRIMARY KEY (invitation_id);
--
--
-- --
-- -- TOC entry 3384 (class 2606 OID 24745)
-- -- Name: employer_profiles employerprofile_dic_key; Type: CONSTRAINT; Schema: public; Owner: internhub
-- --
--
ALTER TABLE ONLY public.employer_profiles
    ADD CONSTRAINT employerprofile_dic_key UNIQUE (dic);
--
--
-- --
-- -- TOC entry 3387 (class 2606 OID 24747)
-- -- Name: employer_profiles employerprofile_ico_key; Type: CONSTRAINT; Schema: public; Owner: internhub
-- --
--
ALTER TABLE ONLY public.employer_profiles
    ADD CONSTRAINT employerprofile_ico_key UNIQUE (ico);
--
--
-- --
-- -- TOC entry 3389 (class 2606 OID 24749)
-- -- Name: employer_profiles employerprofile_pkey; Type: CONSTRAINT; Schema: public; Owner: internhub
-- --
--
ALTER TABLE ONLY public.employer_profiles
    ADD CONSTRAINT employerprofile_pkey PRIMARY KEY (employer_id);
--
--
-- --
-- -- TOC entry 3392 (class 2606 OID 24751)
-- -- Name: organization_users organizationuser_pkey; Type: CONSTRAINT; Schema: public; Owner: internhub
-- --
--
ALTER TABLE ONLY public.organization_users
    ADD CONSTRAINT organizationuser_pkey PRIMARY KEY (user_ptr_id);
--
--
-- --
-- -- TOC entry 3396 (class 2606 OID 24753)
-- -- Name: practices practice_pkey; Type: CONSTRAINT; Schema: public; Owner: internhub
-- --
--
ALTER TABLE ONLY public.practices
    ADD CONSTRAINT practice_pkey PRIMARY KEY (practice_id);
--
--
-- --
-- -- TOC entry 3400 (class 2606 OID 24755)
-- -- Name: professor_users professoruser_pkey; Type: CONSTRAINT; Schema: public; Owner: internhub
-- --
--
ALTER TABLE ONLY public.professor_users
    ADD CONSTRAINT professoruser_pkey PRIMARY KEY (staguser_ptr_id);
--
--
-- --
-- -- TOC entry 3403 (class 2606 OID 24757)
-- -- Name: professor_users professoruser_ucit_idno_key; Type: CONSTRAINT; Schema: public; Owner: internhub
-- --
--
ALTER TABLE ONLY public.professor_users
    ADD CONSTRAINT professoruser_ucit_idno_key UNIQUE (ucit_idno);
--
--
-- --
-- -- TOC entry 3405 (class 2606 OID 24759)
-- -- Name: roles role_pkey; Type: CONSTRAINT; Schema: public; Owner: internhub
-- --
--
ALTER TABLE ONLY public.roles
    ADD CONSTRAINT role_pkey PRIMARY KEY (role_id);
--
--
-- --
-- -- TOC entry 3408 (class 2606 OID 24761)
-- -- Name: roles role_role_name_key; Type: CONSTRAINT; Schema: public; Owner: internhub
-- --
--
ALTER TABLE ONLY public.roles
    ADD CONSTRAINT role_role_name_key UNIQUE (role_name);
--
--
-- --
-- -- TOC entry 3410 (class 2606 OID 24763)
-- -- Name: stag_roles stagrole_pkey; Type: CONSTRAINT; Schema: public; Owner: internhub
-- --
--
ALTER TABLE ONLY public.stag_roles
    ADD CONSTRAINT stagrole_pkey PRIMARY KEY (id);
--
--
-- --
-- -- TOC entry 3413 (class 2606 OID 24765)
-- -- Name: stag_roles stagrole_role_key; Type: CONSTRAINT; Schema: public; Owner: internhub
-- --
--
ALTER TABLE ONLY public.stag_roles
    ADD CONSTRAINT stagrole_role_key UNIQUE (role);
--
--
-- --
-- -- TOC entry 3416 (class 2606 OID 24767)
-- -- Name: stag_roles stagrole_role_name_key; Type: CONSTRAINT; Schema: public; Owner: internhub
-- --
--
ALTER TABLE ONLY public.stag_roles
    ADD CONSTRAINT stagrole_role_name_key UNIQUE (role_name);
--
--
-- --
-- -- TOC entry 3418 (class 2606 OID 24769)
-- -- Name: stag_users staguser_pkey; Type: CONSTRAINT; Schema: public; Owner: internhub
-- --
--
ALTER TABLE ONLY public.stag_users
    ADD CONSTRAINT staguser_pkey PRIMARY KEY (user_ptr_id);
--
--
-- --
-- -- TOC entry 3421 (class 2606 OID 24771)
-- -- Name: student_practices student_practices_content_document_id_key; Type: CONSTRAINT; Schema: public; Owner: internhub
-- --
--
ALTER TABLE ONLY public.student_practices
    ADD CONSTRAINT student_practices_content_document_id_key UNIQUE (content_document_id);
--
--
-- --
-- -- TOC entry 3423 (class 2606 OID 24773)
-- -- Name: student_practices student_practices_contract_document_id_key; Type: CONSTRAINT; Schema: public; Owner: internhub
-- --
--
ALTER TABLE ONLY public.student_practices
    ADD CONSTRAINT student_practices_contract_document_id_key UNIQUE (contract_document_id);
--
--
-- --
-- -- TOC entry 3425 (class 2606 OID 24775)
-- -- Name: student_practices student_practices_feedback_document_id_key; Type: CONSTRAINT; Schema: public; Owner: internhub
-- --
--
ALTER TABLE ONLY public.student_practices
    ADD CONSTRAINT student_practices_feedback_document_id_key UNIQUE (feedback_document_id);
--
--
-- --
-- -- TOC entry 3428 (class 2606 OID 24777)
-- -- Name: student_practices studentpractice_pkey; Type: CONSTRAINT; Schema: public; Owner: internhub
-- --
--
ALTER TABLE ONLY public.student_practices
    ADD CONSTRAINT studentpractice_pkey PRIMARY KEY (student_practice_id);
--
--
-- --
-- -- TOC entry 3432 (class 2606 OID 24779)
-- -- Name: student_practices studentpractice_user_id_practice_id_5a83d45c_uniq; Type: CONSTRAINT; Schema: public; Owner: internhub
-- --
--
ALTER TABLE ONLY public.student_practices
    ADD CONSTRAINT studentpractice_user_id_practice_id_5a83d45c_uniq UNIQUE (user_id, practice_id);
--
--
-- --
-- -- TOC entry 3435 (class 2606 OID 24781)
-- -- Name: student_users studentuser_os_cislo_key; Type: CONSTRAINT; Schema: public; Owner: internhub
-- --
--
ALTER TABLE ONLY public.student_users
    ADD CONSTRAINT studentuser_os_cislo_key UNIQUE (os_cislo);
--
--
-- --
-- -- TOC entry 3437 (class 2606 OID 24783)
-- -- Name: student_users studentuser_pkey; Type: CONSTRAINT; Schema: public; Owner: internhub
-- --
--
ALTER TABLE ONLY public.student_users
    ADD CONSTRAINT studentuser_pkey PRIMARY KEY (staguser_ptr_id);
--
--
-- --
-- -- TOC entry 3439 (class 2606 OID 24785)
-- -- Name: student_users studentuser_stag_f_number_key; Type: CONSTRAINT; Schema: public; Owner: internhub
-- --
--
ALTER TABLE ONLY public.student_users
    ADD CONSTRAINT studentuser_stag_f_number_key UNIQUE (stag_f_number);
--
--
-- --
-- -- TOC entry 3442 (class 2606 OID 24787)
-- -- Name: subjects subject_pkey; Type: CONSTRAINT; Schema: public; Owner: internhub
-- --
--
ALTER TABLE ONLY public.subjects
    ADD CONSTRAINT subject_pkey PRIMARY KEY (subject_id);
--
--
-- --
-- -- TOC entry 3445 (class 2606 OID 24789)
-- -- Name: subjects subject_subject_code_key; Type: CONSTRAINT; Schema: public; Owner: internhub
-- --
--
ALTER TABLE ONLY public.subjects
    ADD CONSTRAINT subject_subject_code_key UNIQUE (subject_code);
--
--
-- --
-- -- TOC entry 3447 (class 2606 OID 24791)
-- -- Name: token_blacklist_blacklistedtoken token_blacklist_blacklistedtoken_pkey; Type: CONSTRAINT; Schema: public; Owner: internhub
-- --
--
ALTER TABLE ONLY public.token_blacklist_blacklistedtoken
    ADD CONSTRAINT token_blacklist_blacklistedtoken_pkey PRIMARY KEY (id);
--
--
-- --
-- -- TOC entry 3449 (class 2606 OID 24793)
-- -- Name: token_blacklist_blacklistedtoken token_blacklist_blacklistedtoken_token_id_key; Type: CONSTRAINT; Schema: public; Owner: internhub
-- --
--
ALTER TABLE ONLY public.token_blacklist_blacklistedtoken
    ADD CONSTRAINT token_blacklist_blacklistedtoken_token_id_key UNIQUE (token_id);
--
--
-- --
-- -- TOC entry 3452 (class 2606 OID 24795)
-- -- Name: token_blacklist_outstandingtoken token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_uniq; Type: CONSTRAINT; Schema: public; Owner: internhub
-- --
--
ALTER TABLE ONLY public.token_blacklist_outstandingtoken
    ADD CONSTRAINT token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_uniq UNIQUE (jti);
--
--
-- --
-- -- TOC entry 3454 (class 2606 OID 24797)
-- -- Name: token_blacklist_outstandingtoken token_blacklist_outstandingtoken_pkey; Type: CONSTRAINT; Schema: public; Owner: internhub
-- --
--
ALTER TABLE ONLY public.token_blacklist_outstandingtoken
    ADD CONSTRAINT token_blacklist_outstandingtoken_pkey PRIMARY KEY (id);
--
--
-- --
-- -- TOC entry 3457 (class 2606 OID 24799)
-- -- Name: uploaded_documents uploadeddocument_pkey; Type: CONSTRAINT; Schema: public; Owner: internhub
-- --
--
ALTER TABLE ONLY public.uploaded_documents
    ADD CONSTRAINT uploadeddocument_pkey PRIMARY KEY (document_id);
--
--
-- --
-- -- TOC entry 3472 (class 2606 OID 24801)
-- -- Name: users user_email_key; Type: CONSTRAINT; Schema: public; Owner: internhub
-- --
--
ALTER TABLE ONLY public.users
    ADD CONSTRAINT user_email_key UNIQUE (email);
--
--
-- --
-- -- TOC entry 3460 (class 2606 OID 24803)
-- -- Name: users_groups user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: internhub
-- --
--
ALTER TABLE ONLY public.users_groups
    ADD CONSTRAINT user_groups_pkey PRIMARY KEY (id);
--
--
-- --
-- -- TOC entry 3463 (class 2606 OID 24805)
-- -- Name: users_groups user_groups_user_id_group_id_40beef00_uniq; Type: CONSTRAINT; Schema: public; Owner: internhub
-- --
--
ALTER TABLE ONLY public.users_groups
    ADD CONSTRAINT user_groups_user_id_group_id_40beef00_uniq UNIQUE (user_id, group_id);
--
--
-- --
-- -- TOC entry 3474 (class 2606 OID 24807)
-- -- Name: users user_pkey; Type: CONSTRAINT; Schema: public; Owner: internhub
-- --
--
ALTER TABLE ONLY public.users
    ADD CONSTRAINT user_pkey PRIMARY KEY (user_id);
--
--
-- --
-- -- TOC entry 3481 (class 2606 OID 24809)
-- -- Name: users_user_permissions user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: internhub
-- --
--
ALTER TABLE ONLY public.users_user_permissions
    ADD CONSTRAINT user_user_permissions_pkey PRIMARY KEY (id);
--
--
-- --
-- -- TOC entry 3484 (class 2606 OID 24811)
-- -- Name: users_user_permissions user_user_permissions_user_id_permission_id_7dc6e2e0_uniq; Type: CONSTRAINT; Schema: public; Owner: internhub
-- --
--
ALTER TABLE ONLY public.users_user_permissions
    ADD CONSTRAINT user_user_permissions_user_id_permission_id_7dc6e2e0_uniq UNIQUE (user_id, permission_id);
--
--
-- --
-- -- TOC entry 3478 (class 2606 OID 24813)
-- -- Name: users user_username_key; Type: CONSTRAINT; Schema: public; Owner: internhub
-- --
--
ALTER TABLE ONLY public.users
    ADD CONSTRAINT user_username_key UNIQUE (username);
--
--
-- --
-- -- TOC entry 3465 (class 2606 OID 24815)
-- -- Name: user_subjects usersubject_pkey; Type: CONSTRAINT; Schema: public; Owner: internhub
-- --
--
ALTER TABLE ONLY public.user_subjects
    ADD CONSTRAINT usersubject_pkey PRIMARY KEY (id);
--
--
-- --
-- -- TOC entry 3469 (class 2606 OID 24817)
-- -- Name: user_subjects usersubject_user_id_subject_id_c3084a21_uniq; Type: CONSTRAINT; Schema: public; Owner: internhub
-- --
--
ALTER TABLE ONLY public.user_subjects
    ADD CONSTRAINT usersubject_user_id_subject_id_c3084a21_uniq UNIQUE (user_id, subject_id);
--
--
-- --
-- -- TOC entry 3338 (class 1259 OID 24818)
-- -- Name: actionlog_user_id_6f4a5ced; Type: INDEX; Schema: public; Owner: internhub
-- --
