# Stage 1: Build
ARG NODE_VERSION=18
FROM node:${NODE_VERSION}-alpine as build

WORKDIR /app/frontend

COPY frontend/package*.json ./
RUN npm install --legacy-peer-deps

COPY frontend/ .
RUN npm run build

# Stage 2: Serve
FROM nginx:alpine

COPY --from=build /app/frontend/build /usr/share/nginx/html
COPY .docker/Frontend/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
