# Generated by Django 6.0 on 2025-12-07 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("department", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                ("subject_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "subject_code",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                (
                    "subject_name",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("hours_required", models.IntegerField(blank=True, null=True)),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="subjects",
                        to="department.department",
                    ),
                ),
            ],
            options={
                "db_table": "subjects",
            },
        ),
    ]
