# Generated by Django 6.0 on 2025-12-07 15:44

import django_enumfield.db.fields
import practices.models
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Practice",
            fields=[
                ("practice_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(blank=True, default="", max_length=100)),
                ("description", models.TextField(blank=True, default="")),
                ("responsibilities", models.TextField(blank=True, default="")),
                ("available_positions", models.IntegerField(blank=True, null=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "progress_status",
                    django_enumfield.db.fields.EnumField(
                        enum=practices.models.ProgressStatus
                    ),
                ),
                (
                    "approval_status",
                    django_enumfield.db.fields.EnumField(
                        enum=users.models.ApprovalStatus
                    ),
                ),
                ("is_active", models.BooleanField(blank=True, null=True)),
                ("image_base64", models.TextField(blank=True, default="")),
                ("coefficient", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "practices",
                "ordering": ["-created_at"],
            },
        ),
    ]
