# Generated by Django 5.2.11 on 2026-03-04 18:26

import django_enumfield.db.fields
import practices.models
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("practices", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="practice",
            name="approval_status",
            field=django_enumfield.db.fields.EnumField(
                db_index=True, enum=users.models.ApprovalStatus
            ),
        ),
        migrations.AlterField(
            model_name="practice",
            name="is_active",
            field=models.BooleanField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="practice",
            name="progress_status",
            field=django_enumfield.db.fields.EnumField(
                db_index=True, enum=practices.models.ProgressStatus
            ),
        ),
        migrations.AlterField(
            model_name="practice",
            name="title",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=100
            ),
        ),
    ]
