# Generated by Django 5.2.12 on 2026-03-07 14:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("practices", "0003_alter_practice_approval_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="practice",
            name="skills",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
