# Generated by Django 6.0 on 2025-12-07 15:44

import django.db.models.deletion
import django_enumfield.db.fields
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("department", "0001_initial"),
        ("practices", "0001_initial"),
        ("student_practices", "0001_initial"),
        ("subject", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("password", models.CharField(blank=True, default="", max_length=128)),
                (
                    "username",
                    models.CharField(
                        blank=True, max_length=150, null=True, unique=True
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "title_before",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                (
                    "title_after",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("phone", models.CharField(blank=True, default="", max_length=15)),
                ("is_active", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
                ("is_staff", models.BooleanField(default=False)),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date_joined", models.DateField(blank=True, null=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "polymorphic_ctype",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polymorphic_%(app_label)s.%(class)s_set+",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "db_table": "users",
                "swappable": "AUTH_USER_MODEL",
            },
            managers=[
                ("objects", users.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="EmployerProfile",
            fields=[
                ("employer_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "company_name",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "ico",
                    models.CharField(blank=True, max_length=15, null=True, unique=True),
                ),
                (
                    "dic",
                    models.CharField(blank=True, max_length=15, null=True, unique=True),
                ),
                ("city", models.TextField(blank=True, default="")),
                ("address", models.TextField(blank=True, default="")),
                ("zip_code", models.IntegerField(blank=True, null=True)),
                ("company_profile", models.TextField(blank=True, default="")),
                (
                    "approval_status",
                    django_enumfield.db.fields.EnumField(
                        enum=users.models.ApprovalStatus
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="storage/images/logos"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "employer_profiles",
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                ("role_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "role_name",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                ("description", models.TextField(blank=True, default="")),
            ],
            options={
                "db_table": "roles",
            },
        ),
        migrations.CreateModel(
            name="StagRole",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("role", models.CharField(unique=True)),
                (
                    "role_name",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                ("description", models.TextField(blank=True, default="")),
            ],
            options={
                "db_table": "stag_roles",
            },
        ),
        migrations.CreateModel(
            name="StagUser",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "stag_role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stag_users",
                        to="users.stagrole",
                    ),
                ),
            ],
            options={
                "db_table": "stag_users",
            },
            bases=("users.user",),
            managers=[
                ("objects", users.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="ActionLog",
            fields=[
                ("action_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "action_type",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "object_type",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("object_id", models.IntegerField(blank=True, null=True)),
                ("action_description", models.TextField(blank=True, default="")),
                ("action_date", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="action_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "action_logs",
            },
        ),
        migrations.CreateModel(
            name="OrganizationUser",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization_role",
                    django_enumfield.db.fields.EnumField(
                        blank=True, enum=users.models.OrganizationRole, null=True
                    ),
                ),
                (
                    "employer_profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organization_users",
                        to="users.employerprofile",
                    ),
                ),
            ],
            options={
                "db_table": "organization_users",
            },
            bases=("users.user",),
            managers=[
                ("objects", users.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="ProfessorUser",
            fields=[
                (
                    "staguser_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="users.staguser",
                    ),
                ),
                (
                    "ucit_idno",
                    models.CharField(blank=True, max_length=64, null=True, unique=True),
                ),
                (
                    "department_role",
                    django_enumfield.db.fields.EnumField(
                        blank=True, enum=users.models.DepartmentRole, null=True
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="professor_users",
                        to="department.department",
                    ),
                ),
            ],
            options={
                "db_table": "professor_users",
            },
            bases=("users.staguser",),
            managers=[
                ("objects", users.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="StudentUser",
            fields=[
                (
                    "staguser_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="users.staguser",
                    ),
                ),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True, null=True, upload_to="storage/images/profiles"
                    ),
                ),
                (
                    "os_cislo",
                    models.CharField(blank=True, max_length=64, null=True, unique=True),
                ),
                (
                    "field_of_study",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("year_of_study", models.IntegerField(blank=True, null=True)),
                (
                    "stag_f_number",
                    models.IntegerField(blank=True, null=True, unique=True),
                ),
                ("resume", models.TextField(blank=True, default="")),
                ("additional_info", models.TextField(blank=True, default="")),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "place_of_birth",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("street", models.CharField(blank=True, default="", max_length=100)),
                (
                    "street_number",
                    models.CharField(blank=True, default="", max_length=10),
                ),
                ("zip_code", models.CharField(blank=True, default="", max_length=10)),
                ("city", models.CharField(blank=True, default="", max_length=100)),
                (
                    "specialization",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "practices",
                    models.ManyToManyField(
                        related_name="student_users",
                        through="student_practices.StudentPractice",
                        to="practices.practice",
                    ),
                ),
            ],
            options={
                "db_table": "student_users",
            },
            bases=("users.staguser",),
            managers=[
                ("objects", users.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="UserSubject",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "role",
                    django_enumfield.db.fields.EnumField(
                        enum=users.models.UserSubjectType
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_subjects",
                        to="subject.subject",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_subjects",
                        to="users.staguser",
                    ),
                ),
            ],
            options={
                "db_table": "user_subjects",
                "unique_together": {("user", "subject")},
            },
        ),
    ]
