# Generated by Django 6.0 on 2025-12-13 12:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employerprofile",
            name="city",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="stagrole",
            name="description",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="studentuser",
            name="field_of_study",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(blank=True, default="", max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="title_before",
            field=models.CharField(blank=True, default="", max_length=50, null=True),
        ),
    ]
