# Generated by Django 5.2.11 on 2026-03-04 18:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_studentuser_cv_file_studentuser_favorite_practices_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="organizationuser",
            managers=[],
        ),
        migrations.AlterModelManagers(
            name="professoruser",
            managers=[],
        ),
        migrations.AlterModelManagers(
            name="staguser",
            managers=[],
        ),
        migrations.AlterModelManagers(
            name="studentuser",
            managers=[],
        ),
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
        migrations.AlterField(
            model_name="employerprofile",
            name="company_name",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="employerprofile",
            name="ico",
            field=models.CharField(
                blank=True, db_index=True, max_length=15, null=True, unique=True
            ),
        ),
    ]
